# MCP Server Configuration
mcp:
  enabled: true
  server_url: "http://localhost:9090"

# Database configuration
database:
  type: postgresql
  host: 127.0.0.1
  port: 5432
  name: mcp_hotel_db
  user: postgres
  password: postgres  # You should change this to your actual database password
  ssl_mode: disable

# Server configuration
server:
  host: 0.0.0.0
  port: 5000
  debug: true

# Toolbox configuration
toolbox:
  tools_file: tools.yaml
  cache_dir: .cache

# LLM provider configuration
llm:
  provider: gemini  # Options: gemini, claude
  api_keys:
    gemini: ${GOOGLE_API_KEY}
    claude: ${ANTHROPIC_API_KEY}
  
# Logging configuration
logging:
  level: info  # Options: debug, info, warning, error
  file: logs/mcp-server.log